<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>
<center><b><h1>Viraj Odedra | C5-680 | 23010101178 | 31-12-2025</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>

# Decision Tree Classifier

In [373]:
from sklearn.datasets import load_iris

# Import iris data ser using sklearn

In [375]:
data = load_iris()

In [376]:
df = pd.DataFrame(data.data)
df

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [377]:

data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [378]:
print(type(data))

<class 'sklearn.utils._bunch.Bunch'>

# Importing the libraries

In [380]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Divide the data into input and output

In [382]:
X = data['data']

In [383]:
y = data['target']

In [384]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [386]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fitting DecisionTreeClassifier   on dataset

In [388]:
model = DecisionTreeClassifier()

In [389]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [391]:
from sklearn import tree

In [392]:
%matplotlib qt

In [393]:
# magic command
%whos

Variable                 Type                      Data/Info
------------------------------------------------------------
DecisionTreeClassifier   ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
X                        ndarray                   150x4: 600 elems, type `float64`, 4800 bytes
X_test                   ndarray                   30x4: 120 elems, type `float64`, 960 bytes
X_train                  ndarray                   120x4: 480 elems, type `float64`, 3840 bytes
col                      str                       BMI
cols                     list                      n=5
data                     Bunch                     {'data': array([[5.1, 3.5<...> 'sklearn.datasets.data'}
data2                    DataFrame                      Pregnancies  Glucose<...>n\n[768 rows x 9 columns]
dataframe_columns        function                  <function dataframe_colum<...>ns at 0x000002649DBC02C0>
dataframe_hash           function                  <function dataframe_hash at 0x000002649DBC0EA0>
df                       DataFrame                        0    1    2    3\n<...>n\n[150 rows x 4 columns]
dtypes_str               function                  <function dtypes_str at 0x000002649DBC0F40>
file                     BufferedReader            <_io.BufferedReader name='model.pkl'>
get_dataframes           function                  <function get_dataframes at 0x000002649DC16020>
getpass                  module                    <module 'getpass' from 'E<...>aconda\\Lib\\getpass.py'>
hashlib                  module                    <module 'hashlib' from 'E<...>aconda\\Lib\\hashlib.py'>
import_pandas_safely     function                  <function import_pandas_s<...>ly at 0x000002649DC145E0>
is_data_frame            function                  <function is_data_frame at 0x000002649DC147C0>
json                     module                    <module 'json' from 'E:\\<...>\Lib\\json\\__init__.py'>
load_iris                function                  <function load_iris at 0x00000264F36BC180>
loaded_model             DecisionTreeClassifier    DecisionTreeClassifier()
model                    DecisionTreeClassifier    DecisionTreeClassifier()
model2                   DecisionTreeClassifier    DecisionTreeClassifier()
np                       module                    <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>
pd                       module                    <module 'pandas' from 'E:<...>es\\pandas\\__init__.py'>
pickle                   module                    <module 'pickle' from 'E:<...>naconda\\Lib\\pickle.py'>
plt                      module                    <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
sns                      module                    <module 'seaborn' from 'E<...>s\\seaborn\\__init__.py'>
target                   str                       Outcome
train_test_split         function                  <function train_test_split at 0x00000264F67120C0>
tree                     module                    <module 'sklearn.tree' fr<...>earn\\tree\\__init__.py'>
y                        ndarray                   150: 150 elems, type `int32`, 600 bytes
y_test                   ndarray                   30: 30 elems, type `int32`, 120 bytes
y_train                  ndarray                   120: 120 elems, type `int32`, 480 bytes

In [394]:
tree.plot_tree(model)

[Text(0.3076923076923077, 0.9285714285714286, 'x[3] <= 0.8\ngini = 0.667\nsamples = 120\nvalue = [40, 41, 39]'),
 Text(0.23076923076923078, 0.7857142857142857, 'gini = 0.0\nsamples = 40\nvalue = [40, 0, 0]'),
 Text(0.2692307692307693, 0.8571428571428572, 'True  '),
 Text(0.38461538461538464, 0.7857142857142857, 'x[2] <= 4.75\ngini = 0.5\nsamples = 80\nvalue = [0, 41, 39]'),
 Text(0.34615384615384615, 0.8571428571428572, '  False'),
 Text(0.15384615384615385, 0.6428571428571429, 'x[3] <= 1.65\ngini = 0.053\nsamples = 37\nvalue = [0, 36, 1]'),
 Text(0.07692307692307693, 0.5, 'gini = 0.0\nsamples = 36\nvalue = [0, 36, 0]'),
 Text(0.23076923076923078, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.6153846153846154, 0.6428571428571429, 'x[3] <= 1.75\ngini = 0.206\nsamples = 43\nvalue = [0, 5, 38]'),
 Text(0.38461538461538464, 0.5, 'x[2] <= 4.95\ngini = 0.5\nsamples = 8\nvalue = [0, 4, 4]'),
 Text(0.3076923076923077, 0.35714285714285715, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.46153846153846156, 0.35714285714285715, 'x[3] <= 1.55\ngini = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(0.38461538461538464, 0.21428571428571427, 'gini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.5384615384615384, 0.21428571428571427, 'x[2] <= 5.45\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.46153846153846156, 0.07142857142857142, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.6153846153846154, 0.07142857142857142, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.8461538461538461, 0.5, 'x[2] <= 4.85\ngini = 0.056\nsamples = 35\nvalue = [0, 1, 34]'),
 Text(0.7692307692307693, 0.35714285714285715, 'x[1] <= 3.1\ngini = 0.444\nsamples = 3\nvalue = [0, 1, 2]'),
 Text(0.6923076923076923, 0.21428571428571427, 'gini = 0.0\nsamples = 2\nvalue = [0, 0, 2]'),
 Text(0.8461538461538461, 0.21428571428571427, 'gini = 0.0\nsamples = 1\nvalue = [0, 1, 0]'),
 Text(0.9230769230769231, 0.35714285714285715, 'gini = 0.0\nsamples = 32\nvalue = [0, 0, 32]')]

# Predict the x_test

In [396]:
model.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [397]:
model.score(X_train, y_train)

1.0

In [398]:
model.score(X_test, y_test)

1.0

# Import diabetes.csv dataset

In [400]:
data2 = pd.read_csv("diabetes.csv")

data2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Non Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Non Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,Non Diabetic
764,2,122,70,27,0,36.8,0.340,27,Non Diabetic
765,5,121,72,23,112,26.2,0.245,30,Non Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic
767,1,93,70,31,0,30.4,0.315,23,Non Diabetic

# Check the distribution of the target

In [402]:
data2['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [404]:
data2.isin(values = [0]).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [405]:
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
for col in cols :
      data2[col] = data2[col].replace(0, np.nan)

# Check for missing values

In [407]:
data2.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [409]:
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
for col in cols:
    data2[col] = data2[col].fillna(data2[col].median())

# Visualize Distributions

In [411]:
import matplotlib.pyplot as plt

cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols:
    plt.figure()
    plt.hist(data2[col], bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

In [412]:
import  seaborn as sns
sns.pairplot(data2, hue='Outcome')

# Convert Targer data into interger code

In [414]:
target = 'Outcome'
data2[target] = data2[target].map({
    'Non Diabetic': 0,
    'Diabetic': 1
})

# Divide the data into input and output

In [416]:
X = data2.drop(columns=[target])
y = data2[target]

# Splitting the dataset into the Training set and Test set

In [418]:
from sklearn.model_selection import train_test_split

In [419]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

# Create Model

In [421]:
model2 = DecisionTreeClassifier()

# Fitting DecisionTreeClassifier   on dataset

In [423]:
model2.fit(X_train, y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [425]:
tree.plot_tree(model2)

[Text(0.46883928571428574, 0.9736842105263158, 'x[1] <= 127.5\ngini = 0.453\nsamples = 614\nvalue = [401, 213]'),
 Text(0.21071428571428572, 0.9210526315789473, 'x[7] <= 28.5\ngini = 0.314\nsamples = 390\nvalue = [314, 76]'),
 Text(0.3397767857142857, 0.9473684210526316, 'True  '),
 Text(0.10571428571428572, 0.868421052631579, 'x[5] <= 30.95\ngini = 0.142\nsamples = 221\nvalue = [204, 17]'),
 Text(0.03428571428571429, 0.8157894736842105, 'x[4] <= 48.5\ngini = 0.017\nsamples = 119\nvalue = [118, 1]'),
 Text(0.022857142857142857, 0.7631578947368421, 'x[4] <= 46.5\ngini = 0.133\nsamples = 14\nvalue = [13, 1]'),
 Text(0.011428571428571429, 0.7105263157894737, 'gini = 0.0\nsamples = 13\nvalue = [13, 0]'),
 Text(0.03428571428571429, 0.7105263157894737, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.045714285714285714, 0.7631578947368421, 'gini = 0.0\nsamples = 105\nvalue = [105, 0]'),
 Text(0.17714285714285713, 0.8157894736842105, 'x[5] <= 49.1\ngini = 0.265\nsamples = 102\nvalue = [86, 16]'),
 Text(0.12571428571428572, 0.7631578947368421, 'x[6] <= 0.501\ngini = 0.243\nsamples = 99\nvalue = [85, 14]'),
 Text(0.05714285714285714, 0.7105263157894737, 'x[5] <= 31.1\ngini = 0.144\nsamples = 64\nvalue = [59, 5]'),
 Text(0.045714285714285714, 0.6578947368421053, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.06857142857142857, 0.6578947368421053, 'x[6] <= 0.142\ngini = 0.119\nsamples = 63\nvalue = [59, 4]'),
 Text(0.04, 0.6052631578947368, 'x[1] <= 118.0\ngini = 0.48\nsamples = 5\nvalue = [3, 2]'),
 Text(0.02857142857142857, 0.5526315789473685, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.05142857142857143, 0.5526315789473685, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.09714285714285714, 0.6052631578947368, 'x[5] <= 31.8\ngini = 0.067\nsamples = 58\nvalue = [56, 2]'),
 Text(0.07428571428571429, 0.5526315789473685, 'x[6] <= 0.194\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.06285714285714286, 0.5, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.08571428571428572, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.12, 0.5526315789473685, 'x[0] <= 0.5\ngini = 0.036\nsamples = 55\nvalue = [54, 1]'),
 Text(0.10857142857142857, 0.5, 'x[5] <= 33.9\ngini = 0.142\nsamples = 13\nvalue = [12, 1]'),
 Text(0.09714285714285714, 0.4473684210526316, 'x[7] <= 24.0\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.08571428571428572, 0.39473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.10857142857142857, 0.39473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.12, 0.4473684210526316, 'gini = 0.0\nsamples = 11\nvalue = [11, 0]'),
 Text(0.13142857142857142, 0.5, 'gini = 0.0\nsamples = 42\nvalue = [42, 0]'),
 Text(0.19428571428571428, 0.7105263157894737, 'x[6] <= 0.544\ngini = 0.382\nsamples = 35\nvalue = [26, 9]'),
 Text(0.1657142857142857, 0.6578947368421053, 'x[6] <= 0.512\ngini = 0.444\nsamples = 6\nvalue = [2, 4]'),
 Text(0.15428571428571428, 0.6052631578947368, 'x[7] <= 26.5\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.14285714285714285, 0.5526315789473685, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.1657142857142857, 0.5526315789473685, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.17714285714285713, 0.6052631578947368, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.22285714285714286, 0.6578947368421053, 'x[3] <= 43.5\ngini = 0.285\nsamples = 29\nvalue = [24, 5]'),
 Text(0.21142857142857144, 0.6052631578947368, 'x[2] <= 67.0\ngini = 0.245\nsamples = 28\nvalue = [24, 4]'),
 Text(0.18857142857142858, 0.5526315789473685, 'x[1] <= 89.0\ngini = 0.42\nsamples = 10\nvalue = [7, 3]'),
 Text(0.17714285714285713, 0.5, 'gini = 0.0\nsamples = 4\nvalue = [4, 0]'),
 Text(0.2, 0.5, 'x[3] <= 34.0\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.18857142857142858, 0.4473684210526316, 'x[1] <= 112.5\ngini = 0.375\nsamples = 4\nvalue = [1, 3]'),
 Text(0.17714285714285713, 0.39473684210526316, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.2, 0.39473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.21142857142857144, 0.4473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.2342857142857143, 0.5526315789473685, 'x[5] <= 42.8\ngini = 0.105\nsamples = 18\nvalue = [17, 1]'),
 Text(0.22285714285714286, 0.5, 'gini = 0.0\nsamples = 15\nvalue = [15, 0]'),
 Text(0.24571428571428572, 0.5, 'x[7] <= 22.5\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.2342857142857143, 0.4473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.2571428571428571, 0.4473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.2342857142857143, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.22857142857142856, 0.7631578947368421, 'x[1] <= 119.0\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.21714285714285714, 0.7105263157894737, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.24, 0.7105263157894737, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.3157142857142857, 0.868421052631579, 'x[5] <= 26.35\ngini = 0.454\nsamples = 169\nvalue = [110, 59]'),
 Text(0.30428571428571427, 0.8157894736842105, 'gini = 0.0\nsamples = 33\nvalue = [33, 0]'),
 Text(0.3271428571428571, 0.8157894736842105, 'x[1] <= 94.5\ngini = 0.491\nsamples = 136\nvalue = [77, 59]'),
 Text(0.2742857142857143, 0.7631578947368421, 'x[0] <= 9.5\ngini = 0.128\nsamples = 29\nvalue = [27, 2]'),
 Text(0.26285714285714284, 0.7105263157894737, 'gini = 0.0\nsamples = 22\nvalue = [22, 0]'),
 Text(0.2857142857142857, 0.7105263157894737, 'x[3] <= 30.0\ngini = 0.408\nsamples = 7\nvalue = [5, 2]'),
 Text(0.2742857142857143, 0.6578947368421053, 'gini = 0.0\nsamples = 4\nvalue = [4, 0]'),
 Text(0.29714285714285715, 0.6578947368421053, 'x[5] <= 35.1\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.2857142857142857, 0.6052631578947368, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.30857142857142855, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.38, 0.7631578947368421, 'x[4] <= 112.0\ngini = 0.498\nsamples = 107\nvalue = [50.0, 57.0]'),
 Text(0.3314285714285714, 0.7105263157894737, 'x[6] <= 0.514\ngini = 0.219\nsamples = 16\nvalue = [14, 2]'),
 Text(0.32, 0.6578947368421053, 'gini = 0.0\nsamples = 13\nvalue = [13, 0]'),
 Text(0.34285714285714286, 0.6578947368421053, 'x[7] <= 31.5\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.3314285714285714, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.35428571428571426, 0.6052631578947368, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.42857142857142855, 0.7105263157894737, 'x[6] <= 0.2\ngini = 0.478\nsamples = 91\nvalue = [36, 55]'),
 Text(0.38857142857142857, 0.6578947368421053, 'x[1] <= 97.0\ngini = 0.355\nsamples = 13\nvalue = [10, 3]'),
 Text(0.37714285714285717, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.4, 0.6052631578947368, 'x[7] <= 52.5\ngini = 0.278\nsamples = 12\nvalue = [10, 2]'),
 Text(0.38857142857142857, 0.5526315789473685, 'x[1] <= 102.5\ngini = 0.165\nsamples = 11\nvalue = [10, 1]'),
 Text(0.37714285714285717, 0.5, 'x[1] <= 101.0\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.3657142857142857, 0.4473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.38857142857142857, 0.4473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.4, 0.5, 'gini = 0.0\nsamples = 8\nvalue = [8, 0]'),
 Text(0.4114285714285714, 0.5526315789473685, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.4685714285714286, 0.6578947368421053, 'x[3] <= 28.0\ngini = 0.444\nsamples = 78\nvalue = [26, 52]'),
 Text(0.44571428571428573, 0.6052631578947368, 'x[7] <= 35.0\ngini = 0.231\nsamples = 15\nvalue = [2, 13]'),
 Text(0.4342857142857143, 0.5526315789473685, 'x[2] <= 65.0\ngini = 0.48\nsamples = 5\nvalue = [2, 3]'),
 Text(0.4228571428571429, 0.5, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.44571428571428573, 0.5, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.45714285714285713, 0.5526315789473685, 'gini = 0.0\nsamples = 10\nvalue = [0, 10]'),
 Text(0.49142857142857144, 0.6052631578947368, 'x[1] <= 99.5\ngini = 0.472\nsamples = 63\nvalue = [24, 39]'),
 Text(0.48, 0.5526315789473685, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.5028571428571429, 0.5526315789473685, 'x[6] <= 1.149\ngini = 0.455\nsamples = 60\nvalue = [21, 39]'),
 Text(0.49142857142857144, 0.5, 'x[3] <= 31.5\ngini = 0.441\nsamples = 58\nvalue = [19, 39]'),
 Text(0.4471428571428571, 0.4473684210526316, 'x[2] <= 85.0\ngini = 0.488\nsamples = 38\nvalue = [16, 22]'),
 Text(0.4157142857142857, 0.39473684210526316, 'x[3] <= 29.5\ngini = 0.437\nsamples = 31\nvalue = [10, 21]'),
 Text(0.3871428571428571, 0.34210526315789475, 'x[0] <= 9.5\ngini = 0.365\nsamples = 25\nvalue = [6, 19]'),
 Text(0.36428571428571427, 0.2894736842105263, 'x[4] <= 160.5\ngini = 0.298\nsamples = 22\nvalue = [4, 18]'),
 Text(0.35285714285714287, 0.23684210526315788, 'x[7] <= 30.0\ngini = 0.245\nsamples = 21\nvalue = [3, 18]'),
 Text(0.33, 0.18421052631578946, 'x[0] <= 5.0\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.31857142857142856, 0.13157894736842105, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.3414285714285714, 0.13157894736842105, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.3757142857142857, 0.18421052631578946, 'x[5] <= 29.8\ngini = 0.188\nsamples = 19\nvalue = [2, 17]'),
 Text(0.36428571428571427, 0.13157894736842105, 'x[6] <= 0.246\ngini = 0.408\nsamples = 7\nvalue = [2, 5]'),
 Text(0.35285714285714287, 0.07894736842105263, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.3757142857142857, 0.07894736842105263, 'x[1] <= 117.5\ngini = 0.278\nsamples = 6\nvalue = [1, 5]'),
 Text(0.36428571428571427, 0.02631578947368421, 'gini = 0.0\nsamples = 5\nvalue = [0, 5]'),
 Text(0.3871428571428571, 0.02631578947368421, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.3871428571428571, 0.13157894736842105, 'gini = 0.0\nsamples = 12\nvalue = [0, 12]'),
 Text(0.3757142857142857, 0.23684210526315788, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.41, 0.2894736842105263, 'x[2] <= 67.0\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.3985714285714286, 0.23684210526315788, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.42142857142857143, 0.23684210526315788, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.4442857142857143, 0.34210526315789475, 'x[6] <= 0.245\ngini = 0.444\nsamples = 6\nvalue = [4, 2]'),
 Text(0.4328571428571429, 0.2894736842105263, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.45571428571428574, 0.2894736842105263, 'x[6] <= 0.539\ngini = 0.32\nsamples = 5\nvalue = [4, 1]'),
 Text(0.4442857142857143, 0.23684210526315788, 'gini = 0.0\nsamples = 4\nvalue = [4, 0]'),
 Text(0.46714285714285714, 0.23684210526315788, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.4785714285714286, 0.39473684210526316, 'x[6] <= 0.239\ngini = 0.245\nsamples = 7\nvalue = [6, 1]'),
 Text(0.46714285714285714, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.49, 0.34210526315789475, 'gini = 0.0\nsamples = 6\nvalue = [6, 0]'),
 Text(0.5357142857142857, 0.4473684210526316, 'x[1] <= 122.5\ngini = 0.255\nsamples = 20\nvalue = [3, 17]'),
 Text(0.5242857142857142, 0.39473684210526316, 'x[2] <= 58.0\ngini = 0.105\nsamples = 18\nvalue = [1, 17]'),
 Text(0.5128571428571429, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.5357142857142857, 0.34210526315789475, 'gini = 0.0\nsamples = 17\nvalue = [0, 17]'),
 Text(0.5471428571428572, 0.39473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.5142857142857142, 0.5, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.7269642857142857, 0.9210526315789473, 'x[5] <= 29.95\ngini = 0.475\nsamples = 224\nvalue = [87, 137]'),
 Text(0.5979017857142858, 0.9473684210526316, '  False'),
 Text(0.5857142857142857, 0.868421052631579, 'x[1] <= 146.5\ngini = 0.433\nsamples = 60\nvalue = [41, 19]'),
 Text(0.5371428571428571, 0.8157894736842105, 'x[6] <= 0.407\ngini = 0.245\nsamples = 35\nvalue = [30, 5]'),
 Text(0.5257142857142857, 0.7631578947368421, 'x[6] <= 0.396\ngini = 0.351\nsamples = 22\nvalue = [17, 5]'),
 Text(0.5142857142857142, 0.7105263157894737, 'x[7] <= 27.5\ngini = 0.308\nsamples = 21\nvalue = [17, 4]'),
 Text(0.5028571428571429, 0.6578947368421053, 'gini = 0.0\nsamples = 9\nvalue = [9, 0]'),
 Text(0.5257142857142857, 0.6578947368421053, 'x[7] <= 35.0\ngini = 0.444\nsamples = 12\nvalue = [8, 4]'),
 Text(0.5142857142857142, 0.6052631578947368, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.5371428571428571, 0.6052631578947368, 'x[6] <= 0.273\ngini = 0.198\nsamples = 9\nvalue = [8, 1]'),
 Text(0.5257142857142857, 0.5526315789473685, 'gini = 0.0\nsamples = 7\nvalue = [7, 0]'),
 Text(0.5485714285714286, 0.5526315789473685, 'x[4] <= 132.5\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.5371428571428571, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.56, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.5371428571428571, 0.7105263157894737, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.5485714285714286, 0.7631578947368421, 'gini = 0.0\nsamples = 13\nvalue = [13, 0]'),
 Text(0.6342857142857142, 0.8157894736842105, 'x[7] <= 62.0\ngini = 0.493\nsamples = 25\nvalue = [11.0, 14.0]'),
 Text(0.6228571428571429, 0.7631578947368421, 'x[7] <= 41.0\ngini = 0.463\nsamples = 22\nvalue = [8, 14]'),
 Text(0.5942857142857143, 0.7105263157894737, 'x[3] <= 20.0\ngini = 0.486\nsamples = 12\nvalue = [7, 5]'),
 Text(0.5714285714285714, 0.6578947368421053, 'x[1] <= 183.0\ngini = 0.32\nsamples = 5\nvalue = [1, 4]'),
 Text(0.56, 0.6052631578947368, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.5828571428571429, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.6171428571428571, 0.6578947368421053, 'x[1] <= 178.0\ngini = 0.245\nsamples = 7\nvalue = [6, 1]'),
 Text(0.6057142857142858, 0.6052631578947368, 'gini = 0.0\nsamples = 6\nvalue = [6, 0]'),
 Text(0.6285714285714286, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.6514285714285715, 0.7105263157894737, 'x[7] <= 53.5\ngini = 0.18\nsamples = 10\nvalue = [1, 9]'),
 Text(0.64, 0.6578947368421053, 'gini = 0.0\nsamples = 7\nvalue = [0, 7]'),
 Text(0.6628571428571428, 0.6578947368421053, 'x[1] <= 178.0\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.6514285714285715, 0.6052631578947368, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.6742857142857143, 0.6052631578947368, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.6457142857142857, 0.7631578947368421, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.8682142857142857, 0.868421052631579, 'x[1] <= 165.5\ngini = 0.404\nsamples = 164\nvalue = [46.0, 118.0]'),
 Text(0.7821428571428571, 0.8157894736842105, 'x[7] <= 24.5\ngini = 0.469\nsamples = 109\nvalue = [41, 68]'),
 Text(0.7314285714285714, 0.7631578947368421, 'x[4] <= 260.0\ngini = 0.463\nsamples = 22\nvalue = [14, 8]'),
 Text(0.72, 0.7105263157894737, 'x[5] <= 40.25\ngini = 0.498\nsamples = 15\nvalue = [7, 8]'),
 Text(0.7085714285714285, 0.6578947368421053, 'x[2] <= 73.0\ngini = 0.463\nsamples = 11\nvalue = [7, 4]'),
 Text(0.6971428571428572, 0.6052631578947368, 'x[7] <= 23.5\ngini = 0.5\nsamples = 8\nvalue = [4, 4]'),
 Text(0.6857142857142857, 0.5526315789473685, 'x[6] <= 0.279\ngini = 0.444\nsamples = 6\nvalue = [2, 4]'),
 Text(0.6742857142857143, 0.5, 'x[1] <= 134.0\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.6628571428571428, 0.4473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.6857142857142857, 0.4473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.6971428571428572, 0.5, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.7085714285714285, 0.5526315789473685, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.72, 0.6052631578947368, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.7314285714285714, 0.6578947368421053, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.7428571428571429, 0.7105263157894737, 'gini = 0.0\nsamples = 7\nvalue = [7, 0]'),
 Text(0.8328571428571429, 0.7631578947368421, 'x[6] <= 0.719\ngini = 0.428\nsamples = 87\nvalue = [27.0, 60.0]'),
 Text(0.8028571428571428, 0.7105263157894737, 'x[6] <= 0.672\ngini = 0.465\nsamples = 68\nvalue = [25, 43]'),
 Text(0.7914285714285715, 0.6578947368421053, 'x[2] <= 73.0\ngini = 0.448\nsamples = 65\nvalue = [22, 43]'),
 Text(0.7428571428571429, 0.6052631578947368, 'x[1] <= 164.0\ngini = 0.287\nsamples = 23\nvalue = [4, 19]'),
 Text(0.7314285714285714, 0.5526315789473685, 'x[6] <= 0.319\ngini = 0.236\nsamples = 22\nvalue = [3, 19]'),
 Text(0.72, 0.5, 'x[1] <= 132.0\ngini = 0.444\nsamples = 9\nvalue = [3, 6]'),
 Text(0.7085714285714285, 0.4473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.7314285714285714, 0.4473684210526316, 'x[4] <= 176.5\ngini = 0.245\nsamples = 7\nvalue = [1, 6]'),
 Text(0.72, 0.39473684210526316, 'gini = 0.0\nsamples = 5\nvalue = [0, 5]'),
 Text(0.7428571428571429, 0.39473684210526316, 'x[7] <= 32.5\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.7314285714285714, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.7542857142857143, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.7428571428571429, 0.5, 'gini = 0.0\nsamples = 13\nvalue = [0, 13]'),
 Text(0.7542857142857143, 0.5526315789473685, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.84, 0.6052631578947368, 'x[2] <= 91.0\ngini = 0.49\nsamples = 42\nvalue = [18, 24]'),
 Text(0.8285714285714286, 0.5526315789473685, 'x[7] <= 31.0\ngini = 0.5\nsamples = 36\nvalue = [18, 18]'),
 Text(0.7885714285714286, 0.5, 'x[6] <= 0.316\ngini = 0.397\nsamples = 11\nvalue = [8, 3]'),
 Text(0.7771428571428571, 0.4473684210526316, 'gini = 0.0\nsamples = 5\nvalue = [5, 0]'),
 Text(0.8, 0.4473684210526316, 'x[1] <= 156.0\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.7885714285714286, 0.39473684210526316, 'x[6] <= 0.373\ngini = 0.375\nsamples = 4\nvalue = [3, 1]'),
 Text(0.7771428571428571, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.8, 0.34210526315789475, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.8114285714285714, 0.39473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.8685714285714285, 0.5, 'x[1] <= 143.5\ngini = 0.48\nsamples = 25\nvalue = [10, 15]'),
 Text(0.8457142857142858, 0.4473684210526316, 'x[4] <= 262.5\ngini = 0.473\nsamples = 13\nvalue = [8, 5]'),
 Text(0.8342857142857143, 0.39473684210526316, 'x[6] <= 0.274\ngini = 0.397\nsamples = 11\nvalue = [8, 3]'),
 Text(0.8228571428571428, 0.34210526315789475, 'gini = 0.0\nsamples = 5\nvalue = [5, 0]'),
 Text(0.8457142857142858, 0.34210526315789475, 'x[5] <= 33.8\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.8342857142857143, 0.2894736842105263, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.8571428571428571, 0.2894736842105263, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.8571428571428571, 0.39473684210526316, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.8914285714285715, 0.4473684210526316, 'x[4] <= 112.5\ngini = 0.278\nsamples = 12\nvalue = [2, 10]'),
 Text(0.88, 0.39473684210526316, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9028571428571428, 0.39473684210526316, 'x[4] <= 415.0\ngini = 0.165\nsamples = 11\nvalue = [1, 10]'),
 Text(0.8914285714285715, 0.34210526315789475, 'gini = 0.0\nsamples = 10\nvalue = [0, 10]'),
 Text(0.9142857142857143, 0.34210526315789475, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.8514285714285714, 0.5526315789473685, 'gini = 0.0\nsamples = 6\nvalue = [0, 6]'),
 Text(0.8142857142857143, 0.6578947368421053, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.8628571428571429, 0.7105263157894737, 'x[5] <= 39.8\ngini = 0.188\nsamples = 19\nvalue = [2, 17]'),
 Text(0.8514285714285714, 0.6578947368421053, 'gini = 0.0\nsamples = 14\nvalue = [0, 14]'),
 Text(0.8742857142857143, 0.6578947368421053, 'x[2] <= 80.0\ngini = 0.48\nsamples = 5\nvalue = [2, 3]'),

# Predict the x_test

In [431]:
model2.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
      dtype=int64)

# Display Training Accuracy

In [433]:
train_accuracy = model2.score(X_train, y_train)
print("Training Accuracy:", train_accuracy)

Training Accuracy: 1.0

# Display Test Accuracy

In [435]:
test_accuracy = model2.score(X_test, y_test)
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.7077922077922078

# Confusion Matrix

# Save Model State

In [ ]:
import pickle

In [ ]:
with open("model.pkl", 'wb') as file :
    pickle.dump(model, file)

# Load Model from Disk

In [ ]:
with open('model.pkl', 'rb') as file :
    loaded_model = pickle.load(file)

In [ ]:
loaded_model.predict(X_test)